<?php

return [
    ['numeric' => '004', 'alpha2' => 'AF', 'alpha3' => 'AFG', 'name' => 'Afghanistan', 'currencyCode' => 'AFN', 'currencyName' => 'Afghan Afghani', 'currencySymbol' => '؋', 'dialCode' => '+93'],
    ['numeric' => '008', 'alpha2' => 'AL', 'alpha3' => 'ALB', 'name' => 'Albania', 'currencyCode' => 'ALL', 'currencyName' => 'Albanian Lek', 'currencySymbol' => 'L', 'dialCode' => '+355'],
    ['numeric' => '010', 'alpha2' => 'AQ', 'alpha3' => 'ATA', 'name' => 'Antarctica', 'currencyCode' => null, 'currencyName' => null, 'currencySymbol' => null, 'dialCode' => null],
    ['numeric' => '012', 'alpha2' => 'DZ', 'alpha3' => 'DZA', 'name' => 'Algeria', 'currencyCode' => 'DZD', 'currencyName' => 'Algerian Dinar', 'currencySymbol' => 'د.ج', 'dialCode' => '+213'],
    ['numeric' => '016', 'alpha2' => 'AS', 'alpha3' => 'ASM', 'name' => 'American Samoa', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-684'],
    ['numeric' => '020', 'alpha2' => 'AD', 'alpha3' => 'AND', 'name' => 'Andorra', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+376'],
    ['numeric' => '024', 'alpha2' => 'AO', 'alpha3' => 'AGO', 'name' => 'Angola', 'currencyCode' => 'AOA', 'currencyName' => 'Angolan Kwanza', 'currencySymbol' => 'Kz', 'dialCode' => '+244'],
    ['numeric' => '028', 'alpha2' => 'AG', 'alpha3' => 'ATG', 'name' => 'Antigua and Barbuda', 'currencyCode' => 'XCD', 'currencyName' => 'East Caribbean Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-268'],
    ['numeric' => '031', 'alpha2' => 'AZ', 'alpha3' => 'AZE', 'name' => 'Azerbaijan', 'currencyCode' => 'AZN', 'currencyName' => 'Azerbaijani Manat', 'currencySymbol' => '₼', 'dialCode' => '+994'],
    ['numeric' => '032', 'alpha2' => 'AR', 'alpha3' => 'ARG', 'name' => 'Argentina', 'currencyCode' => 'ARS', 'currencyName' => 'Argentine Peso', 'currencySymbol' => '$', 'dialCode' => '+54'],
    ['numeric' => '036', 'alpha2' => 'AU', 'alpha3' => 'AUS', 'name' => 'Australia', 'currencyCode' => 'AUD', 'currencyName' => 'Australian Dollar', 'currencySymbol' => '$', 'dialCode' => '+61'],
    ['numeric' => '040', 'alpha2' => 'AT', 'alpha3' => 'AUT', 'name' => 'Austria', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+43'],
    ['numeric' => '044', 'alpha2' => 'BS', 'alpha3' => 'BHS', 'name' => 'Bahamas', 'currencyCode' => 'BSD', 'currencyName' => 'Bahamian Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-242'],
    ['numeric' => '048', 'alpha2' => 'BH', 'alpha3' => 'BHR', 'name' => 'Bahrain', 'currencyCode' => 'BHD', 'currencyName' => 'Bahraini Dinar', 'currencySymbol' => '.د.ب', 'dialCode' => '+973'],
    ['numeric' => '050', 'alpha2' => 'BD', 'alpha3' => 'BGD', 'name' => 'Bangladesh', 'currencyCode' => 'BDT', 'currencyName' => 'Bangladeshi Taka', 'currencySymbol' => '৳', 'dialCode' => '+880'],
    ['numeric' => '051', 'alpha2' => 'AM', 'alpha3' => 'ARM', 'name' => 'Armenia', 'currencyCode' => 'AMD', 'currencyName' => 'Armenian Dram', 'currencySymbol' => '֏', 'dialCode' => '+374'],
    ['numeric' => '052', 'alpha2' => 'BB', 'alpha3' => 'BRB', 'name' => 'Barbados', 'currencyCode' => 'BBD', 'currencyName' => 'Barbadian Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-246'],
    ['numeric' => '056', 'alpha2' => 'BE', 'alpha3' => 'BEL', 'name' => 'Belgium', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+32'],
    ['numeric' => '060', 'alpha2' => 'BM', 'alpha3' => 'BMU', 'name' => 'Bermuda', 'currencyCode' => 'BMD', 'currencyName' => 'Bermudian Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-441'],
    ['numeric' => '064', 'alpha2' => 'BT', 'alpha3' => 'BTN', 'name' => 'Bhutan', 'currencyCode' => 'BTN', 'currencyName' => 'Bhutanese Ngultrum', 'currencySymbol' => 'Nu.', 'dialCode' => '+975'],
    ['numeric' => '068', 'alpha2' => 'BO', 'alpha3' => 'BOL', 'name' => 'Bolivia (Plurinational State of)', 'currencyCode' => 'BOB', 'currencyName' => 'Bolivian Boliviano', 'currencySymbol' => 'Bs.', 'dialCode' => '+591'],
    ['numeric' => '070', 'alpha2' => 'BA', 'alpha3' => 'BIH', 'name' => 'Bosnia and Herzegovina', 'currencyCode' => 'BAM', 'currencyName' => 'Bosnia-Herzegovina Convertible Mark', 'currencySymbol' => 'KM', 'dialCode' => '+387'],
    ['numeric' => '072', 'alpha2' => 'BW', 'alpha3' => 'BWA', 'name' => 'Botswana', 'currencyCode' => 'BWP', 'currencyName' => 'Botswana Pula', 'currencySymbol' => 'P', 'dialCode' => '+267'],
    ['numeric' => '074', 'alpha2' => 'BV', 'alpha3' => 'BVT', 'name' => 'Bouvet Island', 'currencyCode' => null, 'currencyName' => null, 'currencySymbol' => null, 'dialCode' => null],
    ['numeric' => '076', 'alpha2' => 'BR', 'alpha3' => 'BRA', 'name' => 'Brazil', 'currencyCode' => 'BRL', 'currencyName' => 'Brazilian Real', 'currencySymbol' => 'R$', 'dialCode' => '+55'],
    ['numeric' => '084', 'alpha2' => 'BZ', 'alpha3' => 'BLZ', 'name' => 'Belize', 'currencyCode' => 'BZD', 'currencyName' => 'Belize Dollar', 'currencySymbol' => '$', 'dialCode' => '+501'],
    ['numeric' => '086', 'alpha2' => 'IO', 'alpha3' => 'IOT', 'name' => 'British Indian Ocean Territory', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+246'],
    ['numeric' => '090', 'alpha2' => 'SB', 'alpha3' => 'SLB', 'name' => 'Solomon Islands', 'currencyCode' => 'SBD', 'currencyName' => 'Solomon Islands Dollar', 'currencySymbol' => '$', 'dialCode' => '+677'],
    ['numeric' => '092', 'alpha2' => 'VG', 'alpha3' => 'VGB', 'name' => 'Virgin Islands (British)', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-284'],
    ['numeric' => '096', 'alpha2' => 'BN', 'alpha3' => 'BRN', 'name' => 'Brunei Darussalam', 'currencyCode' => 'BND', 'currencyName' => 'Brunei Dollar', 'currencySymbol' => '$', 'dialCode' => '+673'],
    ['numeric' => '100', 'alpha2' => 'BG', 'alpha3' => 'BGR', 'name' => 'Bulgaria', 'currencyCode' => 'BGN', 'currencyName' => 'Bulgarian Lev', 'currencySymbol' => 'лв', 'dialCode' => '+359'],
    ['numeric' => '104', 'alpha2' => 'MM', 'alpha3' => 'MMR', 'name' => 'Myanmar', 'currencyCode' => 'MMK', 'currencyName' => 'Myanmar Kyat', 'currencySymbol' => 'K', 'dialCode' => '+95'],
    ['numeric' => '108', 'alpha2' => 'BI', 'alpha3' => 'BDI', 'name' => 'Burundi', 'currencyCode' => 'BIF', 'currencyName' => 'Burundian Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+257'],
    ['numeric' => '112', 'alpha2' => 'BY', 'alpha3' => 'BLR', 'name' => 'Belarus', 'currencyCode' => 'BYN', 'currencyName' => 'Belarusian Ruble', 'currencySymbol' => 'Br', 'dialCode' => '+375'],
    ['numeric' => '116', 'alpha2' => 'KH', 'alpha3' => 'KHM', 'name' => 'Cambodia', 'currencyCode' => 'KHR', 'currencyName' => 'Cambodian Riel', 'currencySymbol' => '៛', 'dialCode' => '+855'],
    ['numeric' => '120', 'alpha2' => 'CM', 'alpha3' => 'CMR', 'name' => 'Cameroon', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+237'],
    ['numeric' => '124', 'alpha2' => 'CA', 'alpha3' => 'CAN', 'name' => 'Canada', 'currencyCode' => 'CAD', 'currencyName' => 'Canadian Dollar', 'currencySymbol' => '$', 'dialCode' => '+1'],
    ['numeric' => '132', 'alpha2' => 'CV', 'alpha3' => 'CPV', 'name' => 'Cabo Verde', 'currencyCode' => 'CVE', 'currencyName' => 'Cape Verdean Escudo', 'currencySymbol' => '$', 'dialCode' => '+238'],
    ['numeric' => '136', 'alpha2' => 'KY', 'alpha3' => 'CYM', 'name' => 'Cayman Islands', 'currencyCode' => 'KYD', 'currencyName' => 'Cayman Islands Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-345'],
    ['numeric' => '140', 'alpha2' => 'CF', 'alpha3' => 'CAF', 'name' => 'Central African Republic', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+236'],
    ['numeric' => '144', 'alpha2' => 'LK', 'alpha3' => 'LKA', 'name' => 'Sri Lanka', 'currencyCode' => 'LKR', 'currencyName' => 'Sri Lankan Rupee', 'currencySymbol' => 'Rs', 'dialCode' => '+94'],
    ['numeric' => '148', 'alpha2' => 'TD', 'alpha3' => 'TCD', 'name' => 'Chad', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+235'],
    ['numeric' => '152', 'alpha2' => 'CL', 'alpha3' => 'CHL', 'name' => 'Chile', 'currencyCode' => 'CLP', 'currencyName' => 'Chilean Peso', 'currencySymbol' => '$', 'dialCode' => '+56'],
    ['numeric' => '156', 'alpha2' => 'CN', 'alpha3' => 'CHN', 'name' => 'China', 'currencyCode' => 'CNY', 'currencyName' => 'Chinese Yuan', 'currencySymbol' => '¥', 'dialCode' => '+86'],
    ['numeric' => '158', 'alpha2' => 'TW', 'alpha3' => 'TWN', 'name' => 'Taiwan, Province of China', 'currencyCode' => 'TWD', 'currencyName' => 'New Taiwan Dollar', 'currencySymbol' => 'NT$', 'dialCode' => '+886'],
    ['numeric' => '162', 'alpha2' => 'CX', 'alpha3' => 'CXR', 'name' => 'Christmas Island', 'currencyCode' => 'AUD', 'currencyName' => 'Australian Dollar', 'currencySymbol' => '$', 'dialCode' => '+61'],
    ['numeric' => '166', 'alpha2' => 'CC', 'alpha3' => 'CCK', 'name' => 'Cocos (Keeling) Islands', 'currencyCode' => 'AUD', 'currencyName' => 'Australian Dollar', 'currencySymbol' => '$', 'dialCode' => '+61'],
    ['numeric' => '170', 'alpha2' => 'CO', 'alpha3' => 'COL', 'name' => 'Colombia', 'currencyCode' => 'COP', 'currencyName' => 'Colombian Peso', 'currencySymbol' => '$', 'dialCode' => '+57'],
    ['numeric' => '174', 'alpha2' => 'KM', 'alpha3' => 'COM', 'name' => 'Comoros', 'currencyCode' => 'KMF', 'currencyName' => 'Comorian Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+269'],
    ['numeric' => '175', 'alpha2' => 'YT', 'alpha3' => 'MYT', 'name' => 'Mayotte', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+262'],
    ['numeric' => '178', 'alpha2' => 'CG', 'alpha3' => 'COG', 'name' => 'Congo', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+242'],
    ['numeric' => '180', 'alpha2' => 'CD', 'alpha3' => 'COD', 'name' => 'Congo, Democratic Republic of the', 'currencyCode' => 'CDF', 'currencyName' => 'Congolese Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+243'],
    ['numeric' => '184', 'alpha2' => 'CK', 'alpha3' => 'COK', 'name' => 'Cook Islands', 'currencyCode' => 'NZD', 'currencyName' => 'New Zealand Dollar', 'currencySymbol' => '$', 'dialCode' => '+682'],
    ['numeric' => '188', 'alpha2' => 'CR', 'alpha3' => 'CRI', 'name' => 'Costa Rica', 'currencyCode' => 'CRC', 'currencyName' => 'Costa Rican Colón', 'currencySymbol' => '₡', 'dialCode' => '+506'],
    ['numeric' => '191', 'alpha2' => 'HR', 'alpha3' => 'HRV', 'name' => 'Croatia', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+385'],
    ['numeric' => '192', 'alpha2' => 'CU', 'alpha3' => 'CUB', 'name' => 'Cuba', 'currencyCode' => 'CUP', 'currencyName' => 'Cuban Peso', 'currencySymbol' => '$', 'dialCode' => '+53'],
    ['numeric' => '196', 'alpha2' => 'CY', 'alpha3' => 'CYP', 'name' => 'Cyprus', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+357'],
    ['numeric' => '203', 'alpha2' => 'CZ', 'alpha3' => 'CZE', 'name' => 'Czechia', 'currencyCode' => 'CZK', 'currencyName' => 'Czech Koruna', 'currencySymbol' => 'Kč', 'dialCode' => '+420'],
    ['numeric' => '204', 'alpha2' => 'BJ', 'alpha3' => 'BEN', 'name' => 'Benin', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+229'],
    ['numeric' => '208', 'alpha2' => 'DK', 'alpha3' => 'DNK', 'name' => 'Denmark', 'currencyCode' => 'DKK', 'currencyName' => 'Danish Krone', 'currencySymbol' => 'kr', 'dialCode' => '+45'],
    ['numeric' => '212', 'alpha2' => 'DM', 'alpha3' => 'DMA', 'name' => 'Dominica', 'currencyCode' => 'XCD', 'currencyName' => 'East Caribbean Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-767'],
    ['numeric' => '214', 'alpha2' => 'DO', 'alpha3' => 'DOM', 'name' => 'Dominican Republic', 'currencyCode' => 'DOP', 'currencyName' => 'Dominican Peso', 'currencySymbol' => '$', 'dialCode' => '+1-809'],
    ['numeric' => '218', 'alpha2' => 'EC', 'alpha3' => 'ECU', 'name' => 'Ecuador', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+593'],
    ['numeric' => '222', 'alpha2' => 'SV', 'alpha3' => 'SLV', 'name' => 'El Salvador', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+503'],
    ['numeric' => '226', 'alpha2' => 'GQ', 'alpha3' => 'GNQ', 'name' => 'Equatorial Guinea', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+240'],
    ['numeric' => '231', 'alpha2' => 'ET', 'alpha3' => 'ETH', 'name' => 'Ethiopia', 'currencyCode' => 'ETB', 'currencyName' => 'Ethiopian Birr', 'currencySymbol' => 'Br', 'dialCode' => '+251'],
    ['numeric' => '232', 'alpha2' => 'ER', 'alpha3' => 'ERI', 'name' => 'Eritrea', 'currencyCode' => 'ERN', 'currencyName' => 'Eritrean Nakfa', 'currencySymbol' => 'Nfk', 'dialCode' => '+291'],
    ['numeric' => '233', 'alpha2' => 'EE', 'alpha3' => 'EST', 'name' => 'Estonia', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+372'],
    ['numeric' => '234', 'alpha2' => 'FO', 'alpha3' => 'FRO', 'name' => 'Faroe Islands', 'currencyCode' => 'DKK', 'currencyName' => 'Danish Krone', 'currencySymbol' => 'kr', 'dialCode' => '+298'],
    ['numeric' => '238', 'alpha2' => 'FK', 'alpha3' => 'FLK', 'name' => 'Falkland Islands (Malvinas)', 'currencyCode' => 'FKP', 'currencyName' => 'Falkland Islands Pound', 'currencySymbol' => '£', 'dialCode' => '+500'],
    ['numeric' => '239', 'alpha2' => 'GS', 'alpha3' => 'SGS', 'name' => 'South Georgia and the South Sandwich Islands', 'currencyCode' => 'GBP', 'currencyName' => 'Pound Sterling', 'currencySymbol' => '£', 'dialCode' => '+500'],
    ['numeric' => '242', 'alpha2' => 'FJ', 'alpha3' => 'FJI', 'name' => 'Fiji', 'currencyCode' => 'FJD', 'currencyName' => 'Fijian Dollar', 'currencySymbol' => '$', 'dialCode' => '+679'],
    ['numeric' => '246', 'alpha2' => 'FI', 'alpha3' => 'FIN', 'name' => 'Finland', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+358'],
    ['numeric' => '248', 'alpha2' => 'AX', 'alpha3' => 'ALA', 'name' => 'Åland Islands', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+358'],
    ['numeric' => '250', 'alpha2' => 'FR', 'alpha3' => 'FRA', 'name' => 'France', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+33'],
    ['numeric' => '254', 'alpha2' => 'GF', 'alpha3' => 'GUF', 'name' => 'French Guiana', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+594'],
    ['numeric' => '258', 'alpha2' => 'PF', 'alpha3' => 'PYF', 'name' => 'French Polynesia', 'currencyCode' => 'XPF', 'currencyName' => 'CFP Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+689'],
    ['numeric' => '260', 'alpha2' => 'TF', 'alpha3' => 'ATF', 'name' => 'French Southern Territories', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+262'],
    ['numeric' => '262', 'alpha2' => 'DJ', 'alpha3' => 'DJI', 'name' => 'Djibouti', 'currencyCode' => 'DJF', 'currencyName' => 'Djiboutian Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+253'],
    ['numeric' => '266', 'alpha2' => 'GA', 'alpha3' => 'GAB', 'name' => 'Gabon', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+241'],
    ['numeric' => '268', 'alpha2' => 'GE', 'alpha3' => 'GEO', 'name' => 'Georgia', 'currencyCode' => 'GEL', 'currencyName' => 'Georgian Lari', 'currencySymbol' => '₾', 'dialCode' => '+995'],
    ['numeric' => '270', 'alpha2' => 'GM', 'alpha3' => 'GMB', 'name' => 'Gambia', 'currencyCode' => 'GMD', 'currencyName' => 'Gambian Dalasi', 'currencySymbol' => 'D', 'dialCode' => '+220'],
    ['numeric' => '275', 'alpha2' => 'PS', 'alpha3' => 'PSE', 'name' => 'Palestine, State of', 'currencyCode' => 'ILS', 'currencyName' => 'Israeli New Shekel', 'currencySymbol' => '₪', 'dialCode' => '+970'],
    ['numeric' => '276', 'alpha2' => 'DE', 'alpha3' => 'DEU', 'name' => 'Germany', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+49'],
    ['numeric' => '288', 'alpha2' => 'GH', 'alpha3' => 'GHA', 'name' => 'Ghana', 'currencyCode' => 'GHS', 'currencyName' => 'Ghanaian Cedi', 'currencySymbol' => '₵', 'dialCode' => '+233'],
    ['numeric' => '292', 'alpha2' => 'GI', 'alpha3' => 'GIB', 'name' => 'Gibraltar', 'currencyCode' => 'GIP', 'currencyName' => 'Gibraltar Pound', 'currencySymbol' => '£', 'dialCode' => '+350'],
    ['numeric' => '296', 'alpha2' => 'KI', 'alpha3' => 'KIR', 'name' => 'Kiribati', 'currencyCode' => 'AUD', 'currencyName' => 'Australian Dollar', 'currencySymbol' => '$', 'dialCode' => '+686'],
    ['numeric' => '300', 'alpha2' => 'GR', 'alpha3' => 'GRC', 'name' => 'Greece', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+30'],
    ['numeric' => '304', 'alpha2' => 'GL', 'alpha3' => 'GRL', 'name' => 'Greenland', 'currencyCode' => 'DKK', 'currencyName' => 'Danish Krone', 'currencySymbol' => 'kr', 'dialCode' => '+299'],
    ['numeric' => '308', 'alpha2' => 'GD', 'alpha3' => 'GRD', 'name' => 'Grenada', 'currencyCode' => 'XCD', 'currencyName' => 'East Caribbean Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-473'],
    ['numeric' => '312', 'alpha2' => 'GP', 'alpha3' => 'GLP', 'name' => 'Guadeloupe', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+590'],
    ['numeric' => '316', 'alpha2' => 'GU', 'alpha3' => 'GUM', 'name' => 'Guam', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-671'],
    ['numeric' => '320', 'alpha2' => 'GT', 'alpha3' => 'GTM', 'name' => 'Guatemala', 'currencyCode' => 'GTQ', 'currencyName' => 'Guatemalan Quetzal', 'currencySymbol' => 'Q', 'dialCode' => '+502'],
    ['numeric' => '324', 'alpha2' => 'GN', 'alpha3' => 'GIN', 'name' => 'Guinea', 'currencyCode' => 'GNF', 'currencyName' => 'Guinean Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+224'],
    ['numeric' => '328', 'alpha2' => 'GY', 'alpha3' => 'GUY', 'name' => 'Guyana', 'currencyCode' => 'GYD', 'currencyName' => 'Guyanese Dollar', 'currencySymbol' => '$', 'dialCode' => '+592'],
    ['numeric' => '332', 'alpha2' => 'HT', 'alpha3' => 'HTI', 'name' => 'Haiti', 'currencyCode' => 'HTG', 'currencyName' => 'Haitian Gourde', 'currencySymbol' => 'G', 'dialCode' => '+509'],
    ['numeric' => '334', 'alpha2' => 'HM', 'alpha3' => 'HMD', 'name' => 'Heard Island and McDonald Islands', 'currencyCode' => null, 'currencyName' => null, 'currencySymbol' => null, 'dialCode' => null],
    ['numeric' => '336', 'alpha2' => 'VA', 'alpha3' => 'VAT', 'name' => 'Holy See', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+39'],
    ['numeric' => '340', 'alpha2' => 'HN', 'alpha3' => 'HND', 'name' => 'Honduras', 'currencyCode' => 'HNL', 'currencyName' => 'Honduran Lempira', 'currencySymbol' => 'L', 'dialCode' => '+504'],
    ['numeric' => '344', 'alpha2' => 'HK', 'alpha3' => 'HKG', 'name' => 'Hong Kong', 'currencyCode' => 'HKD', 'currencyName' => 'Hong Kong Dollar', 'currencySymbol' => '$', 'dialCode' => '+852'],
    ['numeric' => '348', 'alpha2' => 'HU', 'alpha3' => 'HUN', 'name' => 'Hungary', 'currencyCode' => 'HUF', 'currencyName' => 'Hungarian Forint', 'currencySymbol' => 'Ft', 'dialCode' => '+36'],
    ['numeric' => '352', 'alpha2' => 'IS', 'alpha3' => 'ISL', 'name' => 'Iceland', 'currencyCode' => 'ISK', 'currencyName' => 'Icelandic Króna', 'currencySymbol' => 'kr', 'dialCode' => '+354'],
    ['numeric' => '356', 'alpha2' => 'IN', 'alpha3' => 'IND', 'name' => 'India', 'currencyCode' => 'INR', 'currencyName' => 'Indian Rupee', 'currencySymbol' => '₹', 'dialCode' => '+91'],
    ['numeric' => '360', 'alpha2' => 'ID', 'alpha3' => 'IDN', 'name' => 'Indonesia', 'currencyCode' => 'IDR', 'currencyName' => 'Indonesian Rupiah', 'currencySymbol' => 'Rp', 'dialCode' => '+62'],
    ['numeric' => '364', 'alpha2' => 'IR', 'alpha3' => 'IRN', 'name' => 'Iran (Islamic Republic of)', 'currencyCode' => 'IRR', 'currencyName' => 'Iranian Rial', 'currencySymbol' => '﷼', 'dialCode' => '+98'],
    ['numeric' => '368', 'alpha2' => 'IQ', 'alpha3' => 'IRQ', 'name' => 'Iraq', 'currencyCode' => 'IQD', 'currencyName' => 'Iraqi Dinar', 'currencySymbol' => 'ع.د', 'dialCode' => '+964'],
    ['numeric' => '372', 'alpha2' => 'IE', 'alpha3' => 'IRL', 'name' => 'Ireland', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+353'],
    ['numeric' => '376', 'alpha2' => 'IL', 'alpha3' => 'ISR', 'name' => 'Israel', 'currencyCode' => 'ILS', 'currencyName' => 'Israeli New Shekel', 'currencySymbol' => '₪', 'dialCode' => '+972'],
    ['numeric' => '380', 'alpha2' => 'IT', 'alpha3' => 'ITA', 'name' => 'Italy', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+39'],
    ['numeric' => '384', 'alpha2' => 'CI', 'alpha3' => 'CIV', 'name' => "Côte d'Ivoire", 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+225'],
    ['numeric' => '388', 'alpha2' => 'JM', 'alpha3' => 'JAM', 'name' => 'Jamaica', 'currencyCode' => 'JMD', 'currencyName' => 'Jamaican Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-876'],
    ['numeric' => '392', 'alpha2' => 'JP', 'alpha3' => 'JPN', 'name' => 'Japan', 'currencyCode' => 'JPY', 'currencyName' => 'Japanese Yen', 'currencySymbol' => '¥', 'dialCode' => '+81'],
    ['numeric' => '398', 'alpha2' => 'KZ', 'alpha3' => 'KAZ', 'name' => 'Kazakhstan', 'currencyCode' => 'KZT', 'currencyName' => 'Kazakhstani Tenge', 'currencySymbol' => '₸', 'dialCode' => '+7'],
    ['numeric' => '400', 'alpha2' => 'JO', 'alpha3' => 'JOR', 'name' => 'Jordan', 'currencyCode' => 'JOD', 'currencyName' => 'Jordanian Dinar', 'currencySymbol' => 'د.ا', 'dialCode' => '+962'],
    ['numeric' => '404', 'alpha2' => 'KE', 'alpha3' => 'KEN', 'name' => 'Kenya', 'currencyCode' => 'KES', 'currencyName' => 'Kenyan Shilling', 'currencySymbol' => 'KSh', 'dialCode' => '+254'],
    ['numeric' => '408', 'alpha2' => 'KP', 'alpha3' => 'PRK', 'name' => "Korea (Democratic People's Republic of)", 'currencyCode' => 'KPW', 'currencyName' => 'North Korean Won', 'currencySymbol' => '₩', 'dialCode' => '+850'],
    ['numeric' => '410', 'alpha2' => 'KR', 'alpha3' => 'KOR', 'name' => 'Korea, Republic of', 'currencyCode' => 'KRW', 'currencyName' => 'South Korean Won', 'currencySymbol' => '₩', 'dialCode' => '+82'],
    ['numeric' => '414', 'alpha2' => 'KW', 'alpha3' => 'KWT', 'name' => 'Kuwait', 'currencyCode' => 'KWD', 'currencyName' => 'Kuwaiti Dinar', 'currencySymbol' => 'د.ك', 'dialCode' => '+965'],
    ['numeric' => '417', 'alpha2' => 'KG', 'alpha3' => 'KGZ', 'name' => 'Kyrgyzstan', 'currencyCode' => 'KGS', 'currencyName' => 'Kyrgyzstani Som', 'currencySymbol' => 'с', 'dialCode' => '+996'],
    ['numeric' => '418', 'alpha2' => 'LA', 'alpha3' => 'LAO', 'name' => "Lao People's Democratic Republic", 'currencyCode' => 'LAK', 'currencyName' => 'Lao Kip', 'currencySymbol' => '₭', 'dialCode' => '+856'],
    ['numeric' => '422', 'alpha2' => 'LB', 'alpha3' => 'LBN', 'name' => 'Lebanon', 'currencyCode' => 'LBP', 'currencyName' => 'Lebanese Pound', 'currencySymbol' => 'ل.ل', 'dialCode' => '+961'],
    ['numeric' => '426', 'alpha2' => 'LS', 'alpha3' => 'LSO', 'name' => 'Lesotho', 'currencyCode' => 'LSL', 'currencyName' => 'Lesotho Loti', 'currencySymbol' => 'L', 'dialCode' => '+266'],
    ['numeric' => '428', 'alpha2' => 'LV', 'alpha3' => 'LVA', 'name' => 'Latvia', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+371'],
    ['numeric' => '430', 'alpha2' => 'LR', 'alpha3' => 'LBR', 'name' => 'Liberia', 'currencyCode' => 'LRD', 'currencyName' => 'Liberian Dollar', 'currencySymbol' => '$', 'dialCode' => '+231'],
    ['numeric' => '434', 'alpha2' => 'LY', 'alpha3' => 'LBY', 'name' => 'Libya', 'currencyCode' => 'LYD', 'currencyName' => 'Libyan Dinar', 'currencySymbol' => 'ل.د', 'dialCode' => '+218'],
    ['numeric' => '438', 'alpha2' => 'LI', 'alpha3' => 'LIE', 'name' => 'Liechtenstein', 'currencyCode' => 'CHF', 'currencyName' => 'Swiss Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+423'],
    ['numeric' => '440', 'alpha2' => 'LT', 'alpha3' => 'LTU', 'name' => 'Lithuania', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+370'],
    ['numeric' => '442', 'alpha2' => 'LU', 'alpha3' => 'LUX', 'name' => 'Luxembourg', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+352'],
    ['numeric' => '446', 'alpha2' => 'MO', 'alpha3' => 'MAC', 'name' => 'Macao', 'currencyCode' => 'MOP', 'currencyName' => 'Macanese Pataca', 'currencySymbol' => 'MOP$', 'dialCode' => '+853'],
    ['numeric' => '450', 'alpha2' => 'MG', 'alpha3' => 'MDG', 'name' => 'Madagascar', 'currencyCode' => 'MGA', 'currencyName' => 'Malagasy Ariary', 'currencySymbol' => 'Ar', 'dialCode' => '+261'],
    ['numeric' => '454', 'alpha2' => 'MW', 'alpha3' => 'MWI', 'name' => 'Malawi', 'currencyCode' => 'MWK', 'currencyName' => 'Malawian Kwacha', 'currencySymbol' => 'MK', 'dialCode' => '+265'],
    ['numeric' => '458', 'alpha2' => 'MY', 'alpha3' => 'MYS', 'name' => 'Malaysia', 'currencyCode' => 'MYR', 'currencyName' => 'Malaysian Ringgit', 'currencySymbol' => 'RM', 'dialCode' => '+60'],
    ['numeric' => '462', 'alpha2' => 'MV', 'alpha3' => 'MDV', 'name' => 'Maldives', 'currencyCode' => 'MVR', 'currencyName' => 'Maldivian Rufiyaa', 'currencySymbol' => 'Rf', 'dialCode' => '+960'],
    ['numeric' => '466', 'alpha2' => 'ML', 'alpha3' => 'MLI', 'name' => 'Mali', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+223'],
    ['numeric' => '470', 'alpha2' => 'MT', 'alpha3' => 'MLT', 'name' => 'Malta', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+356'],
    ['numeric' => '474', 'alpha2' => 'MQ', 'alpha3' => 'MTQ', 'name' => 'Martinique', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+596'],
    ['numeric' => '478', 'alpha2' => 'MR', 'alpha3' => 'MRT', 'name' => 'Mauritania', 'currencyCode' => 'MRU', 'currencyName' => 'Mauritanian Ouguiya', 'currencySymbol' => 'UM', 'dialCode' => '+222'],
    ['numeric' => '480', 'alpha2' => 'MU', 'alpha3' => 'MUS', 'name' => 'Mauritius', 'currencyCode' => 'MUR', 'currencyName' => 'Mauritian Rupee', 'currencySymbol' => '₨', 'dialCode' => '+230'],
    ['numeric' => '484', 'alpha2' => 'MX', 'alpha3' => 'MEX', 'name' => 'Mexico', 'currencyCode' => 'MXN', 'currencyName' => 'Mexican Peso', 'currencySymbol' => '$', 'dialCode' => '+52'],
    ['numeric' => '492', 'alpha2' => 'MC', 'alpha3' => 'MCO', 'name' => 'Monaco', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+377'],
    ['numeric' => '496', 'alpha2' => 'MN', 'alpha3' => 'MNG', 'name' => 'Mongolia', 'currencyCode' => 'MNT', 'currencyName' => 'Mongolian Tugrik', 'currencySymbol' => '₮', 'dialCode' => '+976'],
    ['numeric' => '498', 'alpha2' => 'MD', 'alpha3' => 'MDA', 'name' => 'Moldova, Republic of', 'currencyCode' => 'MDL', 'currencyName' => 'Moldovan Leu', 'currencySymbol' => 'L', 'dialCode' => '+373'],
    ['numeric' => '499', 'alpha2' => 'ME', 'alpha3' => 'MNE', 'name' => 'Montenegro', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+382'],
    ['numeric' => '500', 'alpha2' => 'MS', 'alpha3' => 'MSR', 'name' => 'Montserrat', 'currencyCode' => 'XCD', 'currencyName' => 'East Caribbean Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-664'],
    ['numeric' => '504', 'alpha2' => 'MA', 'alpha3' => 'MAR', 'name' => 'Morocco', 'currencyCode' => 'MAD', 'currencyName' => 'Moroccan Dirham', 'currencySymbol' => 'د.م.', 'dialCode' => '+212'],
    ['numeric' => '508', 'alpha2' => 'MZ', 'alpha3' => 'MOZ', 'name' => 'Mozambique', 'currencyCode' => 'MZN', 'currencyName' => 'Mozambican Metical', 'currencySymbol' => 'MT', 'dialCode' => '+258'],
    ['numeric' => '512', 'alpha2' => 'OM', 'alpha3' => 'OMN', 'name' => 'Oman', 'currencyCode' => 'OMR', 'currencyName' => 'Omani Rial', 'currencySymbol' => 'ر.ع.', 'dialCode' => '+968'],
    ['numeric' => '516', 'alpha2' => 'NA', 'alpha3' => 'NAM', 'name' => 'Namibia', 'currencyCode' => 'NAD', 'currencyName' => 'Namibian Dollar', 'currencySymbol' => '$', 'dialCode' => '+264'],
    ['numeric' => '520', 'alpha2' => 'NR', 'alpha3' => 'NRU', 'name' => 'Nauru', 'currencyCode' => 'AUD', 'currencyName' => 'Australian Dollar', 'currencySymbol' => '$', 'dialCode' => '+674'],
    ['numeric' => '524', 'alpha2' => 'NP', 'alpha3' => 'NPL', 'name' => 'Nepal', 'currencyCode' => 'NPR', 'currencyName' => 'Nepalese Rupee', 'currencySymbol' => '₨', 'dialCode' => '+977'],
    ['numeric' => '528', 'alpha2' => 'NL', 'alpha3' => 'NLD', 'name' => 'Netherlands', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+31'],
    ['numeric' => '531', 'alpha2' => 'CW', 'alpha3' => 'CUW', 'name' => 'Curaçao', 'currencyCode' => 'ANG', 'currencyName' => 'Netherlands Antillean Guilder', 'currencySymbol' => 'ƒ', 'dialCode' => '+599'],
    ['numeric' => '533', 'alpha2' => 'AW', 'alpha3' => 'ABW', 'name' => 'Aruba', 'currencyCode' => 'AWG', 'currencyName' => 'Aruban Florin', 'currencySymbol' => 'ƒ', 'dialCode' => '+297'],
    ['numeric' => '534', 'alpha2' => 'SX', 'alpha3' => 'SXM', 'name' => 'Sint Maarten (Dutch part)', 'currencyCode' => 'ANG', 'currencyName' => 'Netherlands Antillean Guilder', 'currencySymbol' => 'ƒ', 'dialCode' => '+1-721'],
    ['numeric' => '535', 'alpha2' => 'BQ', 'alpha3' => 'BES', 'name' => 'Bonaire, Sint Eustatius and Saba', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+599'],
    ['numeric' => '540', 'alpha2' => 'NC', 'alpha3' => 'NCL', 'name' => 'New Caledonia', 'currencyCode' => 'XPF', 'currencyName' => 'CFP Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+687'],
    ['numeric' => '548', 'alpha2' => 'VU', 'alpha3' => 'VUT', 'name' => 'Vanuatu', 'currencyCode' => 'VUV', 'currencyName' => 'Vanuatu Vatu', 'currencySymbol' => 'Vt', 'dialCode' => '+678'],
    ['numeric' => '554', 'alpha2' => 'NZ', 'alpha3' => 'NZL', 'name' => 'New Zealand', 'currencyCode' => 'NZD', 'currencyName' => 'New Zealand Dollar', 'currencySymbol' => '$', 'dialCode' => '+64'],
    ['numeric' => '558', 'alpha2' => 'NI', 'alpha3' => 'NIC', 'name' => 'Nicaragua', 'currencyCode' => 'NIO', 'currencyName' => 'Nicaraguan Córdoba', 'currencySymbol' => 'C$', 'dialCode' => '+505'],
    ['numeric' => '562', 'alpha2' => 'NE', 'alpha3' => 'NER', 'name' => 'Niger', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+227'],
    ['numeric' => '566', 'alpha2' => 'NG', 'alpha3' => 'NGA', 'name' => 'Nigeria', 'currencyCode' => 'NGN', 'currencyName' => 'Nigerian Naira', 'currencySymbol' => '₦', 'dialCode' => '+234'],
    ['numeric' => '570', 'alpha2' => 'NU', 'alpha3' => 'NIU', 'name' => 'Niue', 'currencyCode' => 'NZD', 'currencyName' => 'New Zealand Dollar', 'currencySymbol' => '$', 'dialCode' => '+683'],
    ['numeric' => '574', 'alpha2' => 'NF', 'alpha3' => 'NFK', 'name' => 'Norfolk Island', 'currencyCode' => 'AUD', 'currencyName' => 'Australian Dollar', 'currencySymbol' => '$', 'dialCode' => '+672'],
    ['numeric' => '578', 'alpha2' => 'NO', 'alpha3' => 'NOR', 'name' => 'Norway', 'currencyCode' => 'NOK', 'currencyName' => 'Norwegian Krone', 'currencySymbol' => 'kr', 'dialCode' => '+47'],
    ['numeric' => '580', 'alpha2' => 'MP', 'alpha3' => 'MNP', 'name' => 'Northern Mariana Islands', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-670'],
    ['numeric' => '583', 'alpha2' => 'FM', 'alpha3' => 'FSM', 'name' => 'Micronesia (Federated States of)', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+691'],
    ['numeric' => '584', 'alpha2' => 'MH', 'alpha3' => 'MHL', 'name' => 'Marshall Islands', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+692'],
    ['numeric' => '585', 'alpha2' => 'PW', 'alpha3' => 'PLW', 'name' => 'Palau', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+680'],
    ['numeric' => '586', 'alpha2' => 'PK', 'alpha3' => 'PAK', 'name' => 'Pakistan', 'currencyCode' => 'PKR', 'currencyName' => 'Pakistani Rupee', 'currencySymbol' => '₨', 'dialCode' => '+92'],
    ['numeric' => '591', 'alpha2' => 'PA', 'alpha3' => 'PAN', 'name' => 'Panama', 'currencyCode' => 'PAB', 'currencyName' => 'Panamanian Balboa', 'currencySymbol' => 'B/.', 'dialCode' => '+507'],
    ['numeric' => '598', 'alpha2' => 'PG', 'alpha3' => 'PNG', 'name' => 'Papua New Guinea', 'currencyCode' => 'PGK', 'currencyName' => 'Papua New Guinean Kina', 'currencySymbol' => 'K', 'dialCode' => '+675'],
    ['numeric' => '600', 'alpha2' => 'PY', 'alpha3' => 'PRY', 'name' => 'Paraguay', 'currencyCode' => 'PYG', 'currencyName' => 'Paraguayan Guarani', 'currencySymbol' => '₲', 'dialCode' => '+595'],
    ['numeric' => '604', 'alpha2' => 'PE', 'alpha3' => 'PER', 'name' => 'Peru', 'currencyCode' => 'PEN', 'currencyName' => 'Peruvian Sol', 'currencySymbol' => 'S/.', 'dialCode' => '+51'],
    ['numeric' => '608', 'alpha2' => 'PH', 'alpha3' => 'PHL', 'name' => 'Philippines', 'currencyCode' => 'PHP', 'currencyName' => 'Philippine Peso', 'currencySymbol' => '₱', 'dialCode' => '+63'],
    ['numeric' => '612', 'alpha2' => 'PN', 'alpha3' => 'PCN', 'name' => 'Pitcairn', 'currencyCode' => 'NZD', 'currencyName' => 'New Zealand Dollar', 'currencySymbol' => '$', 'dialCode' => '+64'],
    ['numeric' => '616', 'alpha2' => 'PL', 'alpha3' => 'POL', 'name' => 'Poland', 'currencyCode' => 'PLN', 'currencyName' => 'Polish Zloty', 'currencySymbol' => 'zł', 'dialCode' => '+48'],
    ['numeric' => '620', 'alpha2' => 'PT', 'alpha3' => 'PRT', 'name' => 'Portugal', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+351'],
    ['numeric' => '624', 'alpha2' => 'GW', 'alpha3' => 'GNB', 'name' => 'Guinea-Bissau', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+245'],
    ['numeric' => '626', 'alpha2' => 'TL', 'alpha3' => 'TLS', 'name' => 'Timor-Leste', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+670'],
    ['numeric' => '630', 'alpha2' => 'PR', 'alpha3' => 'PRI', 'name' => 'Puerto Rico', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-787'],
    ['numeric' => '634', 'alpha2' => 'QA', 'alpha3' => 'QAT', 'name' => 'Qatar', 'currencyCode' => 'QAR', 'currencyName' => 'Qatari Riyal', 'currencySymbol' => 'ر.ق', 'dialCode' => '+974'],
    ['numeric' => '638', 'alpha2' => 'RE', 'alpha3' => 'REU', 'name' => 'Réunion', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+262'],
    ['numeric' => '642', 'alpha2' => 'RO', 'alpha3' => 'ROU', 'name' => 'Romania', 'currencyCode' => 'RON', 'currencyName' => 'Romanian Leu', 'currencySymbol' => 'lei', 'dialCode' => '+40'],
    ['numeric' => '643', 'alpha2' => 'RU', 'alpha3' => 'RUS', 'name' => 'Russian Federation', 'currencyCode' => 'RUB', 'currencyName' => 'Russian Ruble', 'currencySymbol' => '₽', 'dialCode' => '+7'],
    ['numeric' => '646', 'alpha2' => 'RW', 'alpha3' => 'RWA', 'name' => 'Rwanda', 'currencyCode' => 'RWF', 'currencyName' => 'Rwandan Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+250'],
    ['numeric' => '652', 'alpha2' => 'BL', 'alpha3' => 'BLM', 'name' => 'Saint Barthélemy', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+590'],
    ['numeric' => '654', 'alpha2' => 'SH', 'alpha3' => 'SHN', 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'currencyCode' => 'SHP', 'currencyName' => 'Saint Helena Pound', 'currencySymbol' => '£', 'dialCode' => '+290'],
    ['numeric' => '659', 'alpha2' => 'KN', 'alpha3' => 'KNA', 'name' => 'Saint Kitts and Nevis', 'currencyCode' => 'XCD', 'currencyName' => 'East Caribbean Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-869'],
    ['numeric' => '660', 'alpha2' => 'AI', 'alpha3' => 'AIA', 'name' => 'Anguilla', 'currencyCode' => 'XCD', 'currencyName' => 'East Caribbean Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-264'],
    ['numeric' => '662', 'alpha2' => 'LC', 'alpha3' => 'LCA', 'name' => 'Saint Lucia', 'currencyCode' => 'XCD', 'currencyName' => 'East Caribbean Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-758'],
    ['numeric' => '663', 'alpha2' => 'MF', 'alpha3' => 'MAF', 'name' => 'Saint Martin (French part)', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+590'],
    ['numeric' => '666', 'alpha2' => 'PM', 'alpha3' => 'SPM', 'name' => 'Saint Pierre and Miquelon', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+508'],
    ['numeric' => '670', 'alpha2' => 'VC', 'alpha3' => 'VCT', 'name' => 'Saint Vincent and the Grenadines', 'currencyCode' => 'XCD', 'currencyName' => 'East Caribbean Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-784'],
    ['numeric' => '674', 'alpha2' => 'SM', 'alpha3' => 'SMR', 'name' => 'San Marino', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+378'],
    ['numeric' => '678', 'alpha2' => 'ST', 'alpha3' => 'STP', 'name' => 'Sao Tome and Principe', 'currencyCode' => 'STN', 'currencyName' => 'São Tomé and Príncipe Dobra', 'currencySymbol' => 'Db', 'dialCode' => '+239'],
    ['numeric' => '682', 'alpha2' => 'SA', 'alpha3' => 'SAU', 'name' => 'Saudi Arabia', 'currencyCode' => 'SAR', 'currencyName' => 'Saudi Riyal', 'currencySymbol' => 'ر.س', 'dialCode' => '+966'],
    ['numeric' => '686', 'alpha2' => 'SN', 'alpha3' => 'SEN', 'name' => 'Senegal', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+221'],
    ['numeric' => '688', 'alpha2' => 'RS', 'alpha3' => 'SRB', 'name' => 'Serbia', 'currencyCode' => 'RSD', 'currencyName' => 'Serbian Dinar', 'currencySymbol' => 'дин.', 'dialCode' => '+381'],
    ['numeric' => '690', 'alpha2' => 'SC', 'alpha3' => 'SYC', 'name' => 'Seychelles', 'currencyCode' => 'SCR', 'currencyName' => 'Seychellois Rupee', 'currencySymbol' => '₨', 'dialCode' => '+248'],
    ['numeric' => '694', 'alpha2' => 'SL', 'alpha3' => 'SLE', 'name' => 'Sierra Leone', 'currencyCode' => 'SLL', 'currencyName' => 'Sierra Leonean Leone', 'currencySymbol' => 'Le', 'dialCode' => '+232'],
    ['numeric' => '702', 'alpha2' => 'SG', 'alpha3' => 'SGP', 'name' => 'Singapore', 'currencyCode' => 'SGD', 'currencyName' => 'Singapore Dollar', 'currencySymbol' => '$', 'dialCode' => '+65'],
    ['numeric' => '703', 'alpha2' => 'SK', 'alpha3' => 'SVK', 'name' => 'Slovakia', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+421'],
    ['numeric' => '704', 'alpha2' => 'VN', 'alpha3' => 'VNM', 'name' => 'Viet Nam', 'currencyCode' => 'VND', 'currencyName' => 'Vietnamese Dong', 'currencySymbol' => '₫', 'dialCode' => '+84'],
    ['numeric' => '705', 'alpha2' => 'SI', 'alpha3' => 'SVN', 'name' => 'Slovenia', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+386'],
    ['numeric' => '706', 'alpha2' => 'SO', 'alpha3' => 'SOM', 'name' => 'Somalia', 'currencyCode' => 'SOS', 'currencyName' => 'Somali Shilling', 'currencySymbol' => 'Sh', 'dialCode' => '+252'],
    ['numeric' => '710', 'alpha2' => 'ZA', 'alpha3' => 'ZAF', 'name' => 'South Africa', 'currencyCode' => 'ZAR', 'currencyName' => 'South African Rand', 'currencySymbol' => 'R', 'dialCode' => '+27'],
    ['numeric' => '716', 'alpha2' => 'ZW', 'alpha3' => 'ZWE', 'name' => 'Zimbabwe', 'currencyCode' => 'ZWL', 'currencyName' => 'Zimbabwean Dollar', 'currencySymbol' => '$', 'dialCode' => '+263'],
    ['numeric' => '724', 'alpha2' => 'ES', 'alpha3' => 'ESP', 'name' => 'Spain', 'currencyCode' => 'EUR', 'currencyName' => 'Euro', 'currencySymbol' => '€', 'dialCode' => '+34'],
    ['numeric' => '728', 'alpha2' => 'SS', 'alpha3' => 'SSD', 'name' => 'South Sudan', 'currencyCode' => 'SSP', 'currencyName' => 'South Sudanese Pound', 'currencySymbol' => '£', 'dialCode' => '+211'],
    ['numeric' => '729', 'alpha2' => 'SD', 'alpha3' => 'SDN', 'name' => 'Sudan', 'currencyCode' => 'SDG', 'currencyName' => 'Sudanese Pound', 'currencySymbol' => 'ج.س.', 'dialCode' => '+249'],
    ['numeric' => '740', 'alpha2' => 'SR', 'alpha3' => 'SUR', 'name' => 'Suriname', 'currencyCode' => 'SRD', 'currencyName' => 'Surinamese Dollar', 'currencySymbol' => '$', 'dialCode' => '+597'],
    ['numeric' => '744', 'alpha2' => 'SJ', 'alpha3' => 'SJM', 'name' => 'Svalbard and Jan Mayen', 'currencyCode' => 'NOK', 'currencyName' => 'Norwegian Krone', 'currencySymbol' => 'kr', 'dialCode' => '+47'],
    ['numeric' => '748', 'alpha2' => 'SZ', 'alpha3' => 'SWZ', 'name' => 'Eswatini', 'currencyCode' => 'SZL', 'currencyName' => 'Swazi Lilangeni', 'currencySymbol' => 'L', 'dialCode' => '+268'],
    ['numeric' => '752', 'alpha2' => 'SE', 'alpha3' => 'SWE', 'name' => 'Sweden', 'currencyCode' => 'SEK', 'currencyName' => 'Swedish Krona', 'currencySymbol' => 'kr', 'dialCode' => '+46'],
    ['numeric' => '756', 'alpha2' => 'CH', 'alpha3' => 'CHE', 'name' => 'Switzerland', 'currencyCode' => 'CHF', 'currencyName' => 'Swiss Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+41'],
    ['numeric' => '760', 'alpha2' => 'SY', 'alpha3' => 'SYR', 'name' => 'Syrian Arab Republic', 'currencyCode' => 'SYP', 'currencyName' => 'Syrian Pound', 'currencySymbol' => '£', 'dialCode' => '+963'],
    ['numeric' => '762', 'alpha2' => 'TJ', 'alpha3' => 'TJK', 'name' => 'Tajikistan', 'currencyCode' => 'TJS', 'currencyName' => 'Tajikistani Somoni', 'currencySymbol' => 'ЅМ', 'dialCode' => '+992'],
    ['numeric' => '764', 'alpha2' => 'TH', 'alpha3' => 'THA', 'name' => 'Thailand', 'currencyCode' => 'THB', 'currencyName' => 'Thai Baht', 'currencySymbol' => '฿', 'dialCode' => '+66'],
    ['numeric' => '768', 'alpha2' => 'TG', 'alpha3' => 'TGO', 'name' => 'Togo', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+228'],
    ['numeric' => '772', 'alpha2' => 'TK', 'alpha3' => 'TKL', 'name' => 'Tokelau', 'currencyCode' => 'NZD', 'currencyName' => 'New Zealand Dollar', 'currencySymbol' => '$', 'dialCode' => '+690'],
    ['numeric' => '776', 'alpha2' => 'TO', 'alpha3' => 'TON', 'name' => 'Tonga', 'currencyCode' => 'TOP', 'currencyName' => 'Tongan Paʻanga', 'currencySymbol' => 'T$', 'dialCode' => '+676'],
    ['numeric' => '780', 'alpha2' => 'TT', 'alpha3' => 'TTO', 'name' => 'Trinidad and Tobago', 'currencyCode' => 'TTD', 'currencyName' => 'Trinidad and Tobago Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-868'],
    ['numeric' => '784', 'alpha2' => 'AE', 'alpha3' => 'ARE', 'name' => 'United Arab Emirates', 'currencyCode' => 'AED', 'currencyName' => 'United Arab Emirates Dirham', 'currencySymbol' => 'د.إ', 'dialCode' => '+971'],
    ['numeric' => '788', 'alpha2' => 'TN', 'alpha3' => 'TUN', 'name' => 'Tunisia', 'currencyCode' => 'TND', 'currencyName' => 'Tunisian Dinar', 'currencySymbol' => 'د.ت', 'dialCode' => '+216'],
    ['numeric' => '792', 'alpha2' => 'TR', 'alpha3' => 'TUR', 'name' => 'Türkiye', 'currencyCode' => 'TRY', 'currencyName' => 'Turkish Lira', 'currencySymbol' => '₺', 'dialCode' => '+90'],
    ['numeric' => '795', 'alpha2' => 'TM', 'alpha3' => 'TKM', 'name' => 'Turkmenistan', 'currencyCode' => 'TMT', 'currencyName' => 'Turkmenistani Manat', 'currencySymbol' => 'm', 'dialCode' => '+993'],
    ['numeric' => '796', 'alpha2' => 'TC', 'alpha3' => 'TCA', 'name' => 'Turks and Caicos Islands', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-649'],
    ['numeric' => '798', 'alpha2' => 'TV', 'alpha3' => 'TUV', 'name' => 'Tuvalu', 'currencyCode' => 'AUD', 'currencyName' => 'Australian Dollar', 'currencySymbol' => '$', 'dialCode' => '+688'],
    ['numeric' => '800', 'alpha2' => 'UG', 'alpha3' => 'UGA', 'name' => 'Uganda', 'currencyCode' => 'UGX', 'currencyName' => 'Ugandan Shilling', 'currencySymbol' => 'USh', 'dialCode' => '+256'],
    ['numeric' => '804', 'alpha2' => 'UA', 'alpha3' => 'UKR', 'name' => 'Ukraine', 'currencyCode' => 'UAH', 'currencyName' => 'Ukrainian Hryvnia', 'currencySymbol' => '₴', 'dialCode' => '+380'],
    ['numeric' => '807', 'alpha2' => 'MK', 'alpha3' => 'MKD', 'name' => 'North Macedonia', 'currencyCode' => 'MKD', 'currencyName' => 'Macedonian Denar', 'currencySymbol' => 'ден', 'dialCode' => '+389'],
    ['numeric' => '818', 'alpha2' => 'EG', 'alpha3' => 'EGY', 'name' => 'Egypt', 'currencyCode' => 'EGP', 'currencyName' => 'Egyptian Pound', 'currencySymbol' => '£', 'dialCode' => '+20'],
    ['numeric' => '826', 'alpha2' => 'GB', 'alpha3' => 'GBR', 'name' => 'United Kingdom of Great Britain and Northern Ireland', 'currencyCode' => 'GBP', 'currencyName' => 'British Pound', 'currencySymbol' => '£', 'dialCode' => '+44'],
    ['numeric' => '831', 'alpha2' => 'GG', 'alpha3' => 'GGY', 'name' => 'Guernsey', 'currencyCode' => 'GBP', 'currencyName' => 'British Pound', 'currencySymbol' => '£', 'dialCode' => '+44'],
    ['numeric' => '832', 'alpha2' => 'JE', 'alpha3' => 'JEY', 'name' => 'Jersey', 'currencyCode' => 'GBP', 'currencyName' => 'British Pound', 'currencySymbol' => '£', 'dialCode' => '+44'],
    ['numeric' => '833', 'alpha2' => 'IM', 'alpha3' => 'IMN', 'name' => 'Isle of Man', 'currencyCode' => 'GBP', 'currencyName' => 'British Pound', 'currencySymbol' => '£', 'dialCode' => '+44'],
    ['numeric' => '834', 'alpha2' => 'TZ', 'alpha3' => 'TZA', 'name' => 'Tanzania, United Republic of', 'currencyCode' => 'TZS', 'currencyName' => 'Tanzanian Shilling', 'currencySymbol' => 'TSh', 'dialCode' => '+255'],
    ['numeric' => '840', 'alpha2' => 'US', 'alpha3' => 'USA', 'name' => 'United States of America', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+1'],
    ['numeric' => '850', 'alpha2' => 'VI', 'alpha3' => 'VIR', 'name' => 'Virgin Islands (U.S.)', 'currencyCode' => 'USD', 'currencyName' => 'United States Dollar', 'currencySymbol' => '$', 'dialCode' => '+1-340'],
    ['numeric' => '854', 'alpha2' => 'BF', 'alpha3' => 'BFA', 'name' => 'Burkina Faso', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+226'],
    ['numeric' => '858', 'alpha2' => 'UY', 'alpha3' => 'URY', 'name' => 'Uruguay', 'currencyCode' => 'UYU', 'currencyName' => 'Uruguayan Peso', 'currencySymbol' => '$', 'dialCode' => '+598'],
    ['numeric' => '860', 'alpha2' => 'UZ', 'alpha3' => 'UZB', 'name' => 'Uzbekistan', 'currencyCode' => 'UZS', 'currencyName' => 'Uzbekistani Som', 'currencySymbol' => 'сум', 'dialCode' => '+998'],
    ['numeric' => '862', 'alpha2' => 'VE', 'alpha3' => 'VEN', 'name' => 'Venezuela (Bolivarian Republic of)', 'currencyCode' => 'VES', 'currencyName' => 'Venezuelan Bolívar', 'currencySymbol' => 'Bs.', 'dialCode' => '+58'],
    ['numeric' => '876', 'alpha2' => 'WF', 'alpha3' => 'WLF', 'name' => 'Wallis and Futuna', 'currencyCode' => 'XPF', 'currencyName' => 'CFP Franc', 'currencySymbol' => 'Fr', 'dialCode' => '+681'],
    ['numeric' => '882', 'alpha2' => 'WS', 'alpha3' => 'WSM', 'name' => 'Samoa', 'currencyCode' => 'WST', 'currencyName' => 'Samoan Tala', 'currencySymbol' => 'T', 'dialCode' => '+685'],
    ['numeric' => '887', 'alpha2' => 'YE', 'alpha3' => 'YEM', 'name' => 'Yemen', 'currencyCode' => 'YER', 'currencyName' => 'Yemeni Rial', 'currencySymbol' => '﷼', 'dialCode' => '+967'],
    ['numeric' => '894', 'alpha2' => 'ZM', 'alpha3' => 'ZMB', 'name' => 'Zambia', 'currencyCode' => 'ZMW', 'currencyName' => 'Zambian Kwacha', 'currencySymbol' => 'ZK', 'dialCode' => '+260'],
];